repos:
  - repo: local
    hooks:
      - id: hatch-format
        name: Format code
        entry: hatch fmt --formatter
        language: system
        pass_filenames: false
        types: [python]
        stages: [pre-commit]
      - id: hatch-test-lint
        name: Type linting
        entry: hatch run test-lint
        language: system
        pass_filenames: false
        types: [ python ]
        stages: [ pre-commit ]