name: build-wheels

permissions:
  id-token: write   
  contents: read  

on:
  release:
    types: [published]

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install UV
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.10'

      - name: Install dependencies
        shell: sh
        run: |
          uv sync --all-groups --all-extras

      - name: Build wheel
        shell: sh
        run: uv run hatch build


      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
  
  deploy:
    name: Upload release to PyPI
    needs:
      - build-wheel
    runs-on: ubuntu-latest

    # environment is used by PyPI Trusted Publisher and is strongly encouraged
    # https://docs.pypi.org/trusted-publishers/adding-a-publisher/
    environment:
      name: pypi
      url: https://pypi.org/p/datu-core
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
